### ISSUE TITLE
Typo: redimencionar => redimensionar

### ISSUE THREAD

**Issue by leobessa** [scudelletti/compilando-org-blog#1]
https://github.com/scudelletti/compilando-org-blog/blob/master/_posts/2014-10-02-manipulacao-de-sinais-de-processos-em-ruby-saiba-quando-sua-tela-redimencionou.markdown

**Comment by scudelletti** [comment]
Thank you @leobessa!
Done on ed75e9126dc80f3abdd2b7321eb0480f6c5460dd.
